<html>
<head>
<title>Ura!</title>
</head>
<body>
	<br />
	<br />
	<br />
	<br />
	<center>
		<h2>Welcome to first page, generated by Hello Controller!</h2>
		<h4>${message}</h4>
	</center>
</body>
</html>
